In [0]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd 
import numpy as np
from numpy import nan
from numpy import array
from nltk.tokenize import TreebankWordTokenizer
from keras.layers import Input
from keras.models import Model
from keras.layers import Dense
data = pd.read_csv('/content/drive/My Drive/annotatedData.csv') 



Using TensorFlow backend.


In [0]:
data=data.to_numpy()

In [0]:
x,y=data.shape

In [0]:
x=10000

In [0]:
arr = [[]]
arrclass=[[]]

In [0]:
j=0
i=0
while(i<x):
    arr[j].append(data[i][1])
    arrclass[j].append(data[i][2])
    if(i+1!=x and data[i+1][0]=="na"):
      j=j+1
      i=i+1
      arr.append([]) 
      arrclass.append([])
    i=i+1  

In [0]:
arr

[['Bahubali',
  '2',
  'ke',
  'liye',
  'line',
  'lag',
  'sakte',
  'hai',
  'desh',
  'ke',
  'liye',
  'kyun',
  'lage',
  'line',
  'me',
  '...',
  '#notebandi',
  '#Bahubali2'],
 ['agar',
  '#notebandi',
  'ke',
  'time',
  'political',
  'party',
  'bhi',
  '#rti',
  'ke',
  'daayre',
  'me',
  'aa',
  'jati',
  'to',
  '#sukmaattack',
  '#kashmir',
  'me',
  'patthar',
  'attack',
  'na',
  'hote',
  '@PMOIndia'],
 ['#Notebandi',
  'se',
  'Kuch',
  'fyda',
  'nahi',
  'hua',
  'lekin',
  'yeh',
  'baat',
  'public',
  'tak',
  'nahi',
  'pahuncha',
  'sake',
  'Root',
  'level',
  'se',
  'kaam',
  'nahi',
  'hua'],
 ['kabhi',
  'aap',
  'logo',
  'na',
  'Lokpal',
  'par',
  'baat',
  'ki',
  '?',
  'kyo',
  '?',
  'aakhir',
  'modi',
  'ji',
  'na',
  'kya',
  'de',
  'rakha',
  'hai',
  'media',
  'ko',
  '?',
  'naxali',
  ',',
  'aatankwad',
  '?',
  '#notebandi',
  'sa',
  'kya',
  'mila',
  '?'],
 ['Inle',
  'bas',
  'ki',
  'baat',
  'nahi',
  'hai',
  'vishwas',
  '

In [0]:
uniquewords=[]
uniqueclasses=[]
for i in range(len(arr)):
  for j in range(len(arr[i])):
    if(arr[i][j] not in uniquewords):
      uniquewords.append(arr[i][j])
for i in range(len(arrclass)):
  for j in range(len(arrclass[i])):
    if(arrclass[i][j] not in uniqueclasses):
      uniqueclasses.append(arrclass[i][j])      

In [0]:
uniquewords

['Bahubali',
 '2',
 'ke',
 'liye',
 'line',
 'lag',
 'sakte',
 'hai',
 'desh',
 'kyun',
 'lage',
 'me',
 '...',
 '#notebandi',
 '#Bahubali2',
 'agar',
 'time',
 'political',
 'party',
 'bhi',
 '#rti',
 'daayre',
 'aa',
 'jati',
 'to',
 '#sukmaattack',
 '#kashmir',
 'patthar',
 'attack',
 'na',
 'hote',
 '@PMOIndia',
 '#Notebandi',
 'se',
 'Kuch',
 'fyda',
 'nahi',
 'hua',
 'lekin',
 'yeh',
 'baat',
 'public',
 'tak',
 'pahuncha',
 'sake',
 'Root',
 'level',
 'kaam',
 'kabhi',
 'aap',
 'logo',
 'Lokpal',
 'par',
 'ki',
 '?',
 'kyo',
 'aakhir',
 'modi',
 'ji',
 'kya',
 'de',
 'rakha',
 'media',
 'ko',
 'naxali',
 ',',
 'aatankwad',
 'sa',
 'mila',
 'Inle',
 'bas',
 'vishwas',
 'dila',
 'pana!Ye',
 'kewal',
 'jaisa',
 'disruption',
 'hi',
 'kar',
 'hain',
 'jiska',
 'result',
 'zero',
 '!',
 '@ArvindKejriwal',
 '@DrKumarVishwas',
 '@msisodia',
 '@ashutosh83B',
 '@raghav_chadha',
 'Elections',
 'pehle',
 'tum',
 'logon',
 'ne',
 '#NoteBandi',
 'ka',
 'mudda',
 'uthaya',
 'janta',
 'okat',


In [0]:
cc = pd.DataFrame(np.zeros((len(uniqueclasses), len(uniqueclasses))))
cc.index=uniqueclasses
cc.columns=uniqueclasses
for i in range(cc.shape[0]):
  for j in range(cc.shape[1]):
    if(uniqueclasses[i]==uniqueclasses[j]):
      cc.loc[uniqueclasses[i],uniqueclasses[j]]=1

In [0]:
c = pd.DataFrame(np.zeros((len(uniquewords), len(uniquewords))))
c.index=uniquewords
c.columns=uniquewords
for i in range(c.shape[0]):
  for j in range(c.shape[1]):
    if(uniquewords[i]==uniquewords[j]):
      c.loc[uniquewords[i],uniquewords[j]]=1
window=5
#k=(window-1)/2
tes=[0]*len(uniquewords)
trainX=[]
trainY=[]
for v_s in range(len(arr)):
  for s_v in range(len(arr[v_s])):
     tes=[0]*len(uniquewords)
     for s in range(window):
         if(0<=s_v-2+s  and len(arr[v_s])>s_v-2+s ):
           wor=arr[v_s][s_v-2+s]
           ind=uniquewords.index(wor)
           tes=tes+c[uniquewords[ind]].to_numpy()
     trainX.append(tes) 
     ix=uniqueclasses.index(arrclass[v_s][s_v])
     trainY.append(cc[uniqueclasses[ix]].to_numpy())     

In [0]:
trainX

[array([1., 1., 1., ..., 0., 0., 0.]),
 array([1., 1., 1., ..., 0., 0., 0.]),
 array([1., 1., 1., ..., 0., 0., 0.]),
 array([0., 1., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 

In [0]:
trainY

[array([1., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0.

In [0]:

def define_model1(uniqueclasses):
  sequence_input = Input(shape=(len(uniquewords),))
  dense1 = Dense(128, activation='relu')(sequence_input)
  preds = Dense(len(uniqueclasses), activation='softmax')(dense1)

  model = Model(sequence_input, preds)
  model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['acc'])
  model.summary()
  return model

In [0]:
model=define_model1(uniqueclasses)
model.fit(array(trainX),array(trainY),batch_size=1000,epochs=10,verbose=1)






Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 3510)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               449408    
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 1032      
Total params: 450,440
Trainable params: 450,440
Non-trainable params: 0
_________________________________________________________________
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/10





9603/9603 [==============================] - 1s 101us/step - loss: 1.9615 - acc: 0.6793
Epoch 2/10
9603/9603 [==============================] - 1s 67us/step - loss: 1.6172 - acc: 0.9303
Epoch 3/10
9603/9603 [==============================] - 1s 68us/step - loss: 1.

In [0]:
loss, acc = model.evaluate(array(trainX), array(trainY), verbose=0)

print('Train Accuracy: %f' % (acc*100))

Train Accuracy: 93.147975
