In [1]:
import pandas as pd 
import numpy as np
import math
data=pd.DataFrame({"sentences": ['I enjoy flying','I like NLP','I like deep learning']})
data

sentences
0        I enjoy flying
1            I like NLP
2  I like deep learning

In [2]:
xx=data["sentences"].to_numpy()

In [3]:
from nltk.tokenize import TreebankWordTokenizer
uniquewords=[]
tok1=[]
for j in xx:
  n=TreebankWordTokenizer().tokenize(j)
  tok1.append(n)
  for uw in n:
    if uw not in uniquewords :
        uniquewords.append(uw)

In [4]:
tok1


[['I', 'enjoy', 'flying'],
 ['I', 'like', 'NLP'],
 ['I', 'like', 'deep', 'learning']]

In [5]:
uniquewords


['I', 'enjoy', 'flying', 'like', 'NLP', 'deep', 'learning']

In [6]:
c = pd.DataFrame(np.zeros((len(uniquewords), len(uniquewords))))
c

0    1    2    3    4    5    6
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [7]:
c.index=uniquewords
c.columns=uniquewords
c

I  enjoy  flying  like  NLP  deep  learning
I         0.0    0.0     0.0   0.0  0.0   0.0       0.0
enjoy     0.0    0.0     0.0   0.0  0.0   0.0       0.0
flying    0.0    0.0     0.0   0.0  0.0   0.0       0.0
like      0.0    0.0     0.0   0.0  0.0   0.0       0.0
NLP       0.0    0.0     0.0   0.0  0.0   0.0       0.0
deep      0.0    0.0     0.0   0.0  0.0   0.0       0.0
learning  0.0    0.0     0.0   0.0  0.0   0.0       0.0

In [8]:
for i in range(c.shape[0]):
  for j in range(c.shape[1]):
    if(uniquewords[i]==uniquewords[j]):
      c.loc[uniquewords[i],uniquewords[j]]=1

In [9]:
c

I  enjoy  flying  like  NLP  deep  learning
I         1.0    0.0     0.0   0.0  0.0   0.0       0.0
enjoy     0.0    1.0     0.0   0.0  0.0   0.0       0.0
flying    0.0    0.0     1.0   0.0  0.0   0.0       0.0
like      0.0    0.0     0.0   1.0  0.0   0.0       0.0
NLP       0.0    0.0     0.0   0.0  1.0   0.0       0.0
deep      0.0    0.0     0.0   0.0  0.0   1.0       0.0
learning  0.0    0.0     0.0   0.0  0.0   0.0       1.0

In [10]:
window=5
k=(window-1)/2
tes=[0]*len(uniquewords)
trainY=[]
for v_s in range(len(tok1)):
  for s_v in range(len(tok1[v_s])):
     tes=[0]*len(uniquewords)
     for s in range(window):
         if(0<=s_v-2+s  and len(tok1[v_s])>s_v-2+s  and s_v-2+s!=s_v):
           wor=tok1[v_s][s_v-2+s]
           ind=uniquewords.index(wor)
           tes=tes+c[uniquewords[ind]].to_numpy()
     trainY.append([tes])      
     #print(tes)    
vsv=c.to_numpy()
trainX=[]
for v_s in range(len(tok1)):
  for s_v in range(len(tok1[v_s])):
    idx=uniquewords.index(tok1[v_s][s_v])
    trainX.append([vsv[idx]])      

In [11]:
trainX

[[array([1., 0., 0., 0., 0., 0., 0.])],
 [array([0., 1., 0., 0., 0., 0., 0.])],
 [array([0., 0., 1., 0., 0., 0., 0.])],
 [array([1., 0., 0., 0., 0., 0., 0.])],
 [array([0., 0., 0., 1., 0., 0., 0.])],
 [array([0., 0., 0., 0., 1., 0., 0.])],
 [array([1., 0., 0., 0., 0., 0., 0.])],
 [array([0., 0., 0., 1., 0., 0., 0.])],
 [array([0., 0., 0., 0., 0., 1., 0.])],
 [array([0., 0., 0., 0., 0., 0., 1.])]]

In [12]:
trainY

[[array([0., 1., 1., 0., 0., 0., 0.])],
 [array([1., 0., 1., 0., 0., 0., 0.])],
 [array([1., 1., 0., 0., 0., 0., 0.])],
 [array([0., 0., 0., 1., 1., 0., 0.])],
 [array([1., 0., 0., 0., 1., 0., 0.])],
 [array([1., 0., 0., 1., 0., 0., 0.])],
 [array([0., 0., 0., 1., 0., 1., 0.])],
 [array([1., 0., 0., 0., 0., 1., 1.])],
 [array([1., 0., 0., 1., 0., 0., 1.])],
 [array([0., 0., 0., 1., 0., 1., 0.])]]

In [13]:
n=len(uniquewords)
m=5

In [14]:
u=np.random.rand(n, m)
#u=np.ones([n, m])
z=[np.ones([m])]
v=np.random.rand(m, n)
#v=np.ones([m, n])
a=[np.zeros([n])]
s=[np.zeros([n])]


In [15]:
def dot(fir,sec):
  result=np.zeros([len(fir), len(sec[0])])
  for i in range(len(fir)):  
    for j in range(len(sec[0])):
        for k in range(len(sec)): 
            result[i][j] =  (fir[i][k] * sec[k][j] ) + result[i][j] 
  #print(result,"****************************************")          
  return result         

In [16]:
def dotvu(a,c,b): 
  if(b==0):
    mm,nn=n,m 
  else:
    mm,nn=m,n  
  xx=np.zeros([nn, mm])
  xxt=np.zeros([mm, nn])
  for i in range(nn):
      [xx[i]]=dot(a,c[i])
  for ii in range(len(xxt)):
    for jj in range(len(xxt[0])):
      xxt[ii][jj]=xx[jj][ii]   
  return xxt    

In [17]:

def softmax(arra):
  c=0
  for j in range(len(arra[0])):
    c=c+math.exp(arra[0][j])
  res=[[0]*len(arra[0])]
  for i in range(len(arra[0])):
    res[0][i]=math.exp(arra[0][i])/c
  return res  


In [18]:
def ebys(jebyjs):
  for i in range(n):
    if(y[0][i]==1):
      if(s[0][i]!=0):
         jebyjs[0][i]=-1*(y[0][i]/s[0][i])
    if(y[0][i]==0):
      if(s[0][i]!=1):
         jebyjs[0][i]=(1-y[0][i])/(1-s[0][i])    
  return jebyjs  


In [19]:
def sbya(jsbyja):
  for i in range(n):
    for j in range(n):
      if(i==j):
       jsbyja[i][j]=s[0][i]*(1-s[0][j])
      else:
       jsbyja[i][j]=s[0][i]*(-s[0][j]) 
  return jsbyja

In [20]:
def abyv(jabyjv):
  for i in range(n):
    for j in range(i,i+1):
      for k in range(m):
        jabyjv[i][j][k]=z[0][k]
  return jabyjv      


In [21]:
def abyz(jabyjz):
  for i in range(n):
    for j in range(m):
      jabyjz[i][j]=v[j][i]
  return jabyjz    

In [22]:
def zbyu(jzbyju):
  for i in range(m):
    for j in range(i,i+1):
      for k in range(n):
        jzbyju[i][j][k]=x[0][k]
  return jzbyju  

In [23]:
def differentiation():
  jebyjs=[np.zeros([n])]
  jsbyja=np.zeros([n, n])
  jabyjv=np.zeros([n,n,m])
  jabyjz=np.zeros([n, m])
  jzbyju=np.zeros([m,m,n])
  #print(ebys(jebyjs),"     e s     **")
  #print(sbya(jsbyja),"     s a     **")
  #print(abyv(jabyjv),"     a v     **")
  #print(abyz(jabyjz),"     a z     **")
  #print(zbyu(jzbyju),"     z u     **")
  jebyjs,jsbyja,jabyjv,jabyjz,jzbyju=ebys(jebyjs),sbya(jsbyja),abyv(jabyjv),abyz(jabyjz),zbyu(jzbyju)
  #print(dot(jebyjs,jsbyja),"        essa")
  #print(dotvu(dot(jebyjs,jsbyja),jabyjv,1),"      essaav")
  derivativev=dotvu(dot(jebyjs,jsbyja),jabyjv,1)
  #print(dot(jebyjs,jsbyja),"          essa ")
  #print(dot(dot(jebyjs,jsbyja),jabyjz),"          essaaz ")
  #print(dotvu(dot(dot(jebyjs,jsbyja),jabyjz),jzbyju,0),"                essazzu")
  derivativeu=dotvu(dot(dot(jebyjs,jsbyja),jabyjz),jzbyju,0)
  #print(np.shape(derivativev))
  #print(np.shape(derivativeu))
  return [derivativev,derivativeu]


In [24]:
print("train ",np.shape(trainX[0]),"  * u ",np.shape(u),"  = z ",np.shape(z),"  * v ",np.shape(v),"  = a ",np.shape(a),"  = s ",np.shape(s))

train  (1, 7)   * u  (7, 5)   = z  (1, 5)   * v  (5, 7)   = a  (1, 7)   = s  (1, 7)


In [25]:
no_of_inst=len(trainX)

In [26]:
epochs=1000
for no_epochs in range(epochs):
    for instance in range(no_of_inst):
        z=dot(trainX[instance],u)
        a=dot(z,v)
        s=softmax(a)
        x=trainX[instance]
        y=trainY[instance]
        #print(z," z    \n",a,"  a    \n",s,"  s    \n",x,"    x    \n",y,"   y    \n",u,"   u    \n",v,"    v   \n")
        [diffv,diffu]=differentiation()
        v=np.subtract(v,0.01*diffv)
        u=np.subtract(u,0.01*diffu)
    


In [27]:
v

array([[ 1.01199643, -1.00480717, -0.66843198,  0.47083821, -0.68049699,
         0.60156729,  2.29041588],
       [ 1.05726172, -1.03335879, -0.34332795,  0.3909997 ,  1.1001293 ,
         1.57768898, -0.02139698],
       [ 1.57674208, -0.0577365 ,  1.91341316,  1.92632243, -0.81390074,
        -0.47720658, -0.10161925],
       [ 2.89454027,  1.49461188,  0.27607549, -0.77922664,  0.33666586,
        -1.12549189,  1.00343051],
       [ 0.38092402,  1.57891294, -1.09057981,  2.29814138, -0.17522562,
         0.48615413,  0.2495325 ]])

In [28]:
u

array([[-1.46966047,  0.00528062,  0.10771702, -1.13754411,  0.41482142],
       [-0.1876325 ,  0.06814988,  2.09943132,  1.12919945, -1.38419662],
       [-0.58174942, -0.58528774,  0.2763985 ,  2.47938488,  1.27960295],
       [ 0.85934674,  1.90150592, -0.97047261,  0.86389538, -0.52636016],
       [ 0.75936446,  1.14738769,  2.11489233,  0.74220427,  1.64790465],
       [ 2.2892304 ,  0.11499007,  1.06852536,  0.44791337,  1.34305336],
       [ 0.55323572,  1.10369146,  0.10767998, -1.98688004,  1.0072361 ]])

In [29]:
diffu

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.00407024, -0.01808017, -0.00523543,  0.03733136, -0.01774418]])

In [30]:
diffv

array([[ 2.20321404e-04,  3.25027674e-04,  7.93173823e-04,
        -2.00106924e-03,  6.45083689e-03, -1.00483029e-02,
         4.26001234e-03],
       [ 4.39496032e-04,  6.48363576e-04,  1.58221917e-03,
        -3.99172289e-03,  1.28680971e-02, -2.00443043e-02,
         8.49785127e-03],
       [ 4.28649349e-05,  6.32362079e-05,  1.54317028e-04,
        -3.89320788e-04,  1.25505148e-03, -1.95496144e-03,
         8.28812582e-04],
       [-7.91167550e-04, -1.16716463e-03, -2.84826340e-03,
         7.18577959e-03, -2.31647617e-02,  3.60831542e-02,
        -1.52975765e-02],
       [ 4.01082019e-04,  5.91693561e-04,  1.44392580e-03,
        -3.64282760e-03,  1.17433651e-02, -1.82923381e-02,
         7.75509924e-03]])