In [1]:
import nltk
import numpy as np
import pandas as pd
np.set_printoptions(linewidth=120)

In [5]:
a='जीवाणु एक एककोशिकीय जीव है | इसका आकार कुछ मिलिमीटर तक ही होता है | इनकी आकृति गोल या मुक्त-चक्राकार से लेकर छङा, आदि आकार की हो सकती है| ये प्रोकैरियोटिक कोशिका भित्तियुक्त, एककोशकीय सरल जीव हैं जो प्रायः सर्वत्र पाये जाते है| ये पृथ्वी पर मिट्टी में, अम्लीय गर्म जल-धाराओं में, नाभिकीय पदार्थों में, जल में,भू-पपड़ी में, यहां तक की कार्बनिक पदार्थों में तथा पौधौं एवं जन्तुओं के शरीर के भीतर भी पाये जाते हैं| साधारणतः एक ग्राम मिट्टी में ४ करोड़ जीवाणु कोष तथा १ मिलीलीटर जल में १० लाख जीवाणु पाएं जाते हैं| संपूर्ण पृथ्वी पर अनुमानतः लगभग ५1१०३० जीवाणु पाएं जाते हैं|जो संसार के बायोमास का एक बहुत बड़ा भाग है| ये कई तत्वों के चक्र में बहुत महत्वपूर्ण भूमिका अदा करते हैं, जैसे कि वायुमंडलिए नाइट्रोजन के स्थीरीकरण में| हलाकि बहुत सारे वंश के जीवाणुओं का श्रेणी विभाजन भी नहीं हुआ है तथापि लगभग आधे जातियों को किसी न किसी प्रयोगशाला में उगाया जा चुका है| जीवाणुओं का अध्ययन बैक्टिरियोलोजी के अन्तर्गत किया जाता है जो कि सूक्ष्मजैविकी की ही एक शाखा है|'

In [6]:
sentences=a.split('|')
sentences

['जीवाणु एक एककोशिकीय जीव है ',
 ' इसका आकार कुछ मिलिमीटर तक ही होता है ',
 ' इनकी आकृति गोल या मुक्त-चक्राकार से लेकर छङा, आदि आकार की हो सकती है',
 ' ये प्रोकैरियोटिक कोशिका भित्तियुक्त, एककोशकीय सरल जीव हैं जो प्रायः सर्वत्र पाये जाते है',
 ' ये पृथ्वी पर मिट्टी में, अम्लीय गर्म जल-धाराओं में, नाभिकीय पदार्थों में, जल में,भू-पपड़ी में, यहां तक की कार्बनिक पदार्थों में तथा पौधौं एवं जन्तुओं के शरीर के भीतर भी पाये जाते हैं',
 ' साधारणतः एक ग्राम मिट्टी में ४ करोड़ जीवाणु कोष तथा १ मिलीलीटर जल में १० लाख जीवाणु पाएं जाते हैं',
 ' संपूर्ण पृथ्वी पर अनुमानतः लगभग ५1१०३० जीवाणु पाएं जाते हैं',
 'जो संसार के बायोमास का एक बहुत बड़ा भाग है',
 ' ये कई तत्वों के चक्र में बहुत महत्वपूर्ण भूमिका अदा करते हैं, जैसे कि वायुमंडलिए नाइट्रोजन के स्थीरीकरण में',
 ' हलाकि बहुत सारे वंश के जीवाणुओं का श्रेणी विभाजन भी नहीं हुआ है तथापि लगभग आधे जातियों को किसी न किसी प्रयोगशाला में उगाया जा चुका है',
 ' जीवाणुओं का अध्ययन बैक्टिरियोलोजी के अन्तर्गत किया जाता है जो कि सूक्ष्मजैविकी की ही एक शाखा है',
 

In [7]:
#import regex
import re
from string import punctuation

#start process_tweet
def processTweet(tweet):
    tweet = re.sub('[\s]+', ' ', tweet)
   
    tweet=''.join(c for c in tweet if not c.isdigit())
   
    tweet=''.join(c for c in tweet if c not in punctuation)
    tweet=re.sub(' +', ' ', tweet) 
    tweet = tweet.strip('\'"')
    tweet=tweet.strip()
   
    return tweet

x=[]
for i in sentences:
    x.append(processTweet(i))
x=x[:-1]
x

['जीवाणु एक एककोशिकीय जीव है',
 'इसका आकार कुछ मिलिमीटर तक ही होता है',
 'इनकी आकृति गोल या मुक्तचक्राकार से लेकर छङा आदि आकार की हो सकती है',
 'ये प्रोकैरियोटिक कोशिका भित्तियुक्त एककोशकीय सरल जीव हैं जो प्रायः सर्वत्र पाये जाते है',
 'ये पृथ्वी पर मिट्टी में अम्लीय गर्म जलधाराओं में नाभिकीय पदार्थों में जल मेंभूपपड़ी में यहां तक की कार्बनिक पदार्थों में तथा पौधौं एवं जन्तुओं के शरीर के भीतर भी पाये जाते हैं',
 'साधारणतः एक ग्राम मिट्टी में करोड़ जीवाणु कोष तथा मिलीलीटर जल में लाख जीवाणु पाएं जाते हैं',
 'संपूर्ण पृथ्वी पर अनुमानतः लगभग जीवाणु पाएं जाते हैं',
 'जो संसार के बायोमास का एक बहुत बड़ा भाग है',
 'ये कई तत्वों के चक्र में बहुत महत्वपूर्ण भूमिका अदा करते हैं जैसे कि वायुमंडलिए नाइट्रोजन के स्थीरीकरण में',
 'हलाकि बहुत सारे वंश के जीवाणुओं का श्रेणी विभाजन भी नहीं हुआ है तथापि लगभग आधे जातियों को किसी न किसी प्रयोगशाला में उगाया जा चुका है',
 'जीवाणुओं का अध्ययन बैक्टिरियोलोजी के अन्तर्गत किया जाता है जो कि सूक्ष्मजैविकी की ही एक शाखा है']

In [8]:
sentences=x

In [9]:
vocab=list(set((" ".join(x)).split()))
vocab

['भीतर',
 'पृथ्वी',
 'तथा',
 'मेंभूपपड़ी',
 'जीवाणु',
 'पाये',
 'लगभग',
 'यहां',
 'बड़ा',
 'को',
 'में',
 'मुक्तचक्राकार',
 'जातियों',
 'तत्वों',
 'बायोमास',
 'लाख',
 'पदार्थों',
 'जाता',
 'किया',
 'से',
 'प्रायः',
 'भाग',
 'प्रयोगशाला',
 'आदि',
 'कि',
 'एककोशिकीय',
 'भूमिका',
 'उगाया',
 'प्रोकैरियोटिक',
 'कुछ',
 'नाइट्रोजन',
 'होता',
 'आकार',
 'भित्तियुक्त',
 'या',
 'लेकर',
 'इनकी',
 'कार्बनिक',
 'अनुमानतः',
 'किसी',
 'है',
 'विभाजन',
 'चक्र',
 'पाएं',
 'गर्म',
 'एवं',
 'संपूर्ण',
 'इसका',
 'मिट्टी',
 'हुआ',
 'भी',
 'कई',
 'वायुमंडलिए',
 'वंश',
 'जो',
 'शरीर',
 'तथापि',
 'चुका',
 'कोशिका',
 'हलाकि',
 'श्रेणी',
 'कोष',
 'गोल',
 'ग्राम',
 'बैक्टिरियोलोजी',
 'जल',
 'महत्वपूर्ण',
 'सकती',
 'हैं',
 'करते',
 'पर',
 'जीव',
 'सर्वत्र',
 'की',
 'सूक्ष्मजैविकी',
 'जन्तुओं',
 'आकृति',
 'बहुत',
 'आधे',
 'अध्ययन',
 'सारे',
 'अम्लीय',
 'नहीं',
 'करोड़',
 'सरल',
 'पौधौं',
 'अदा',
 'संसार',
 'जा',
 'एक',
 'छङा',
 'का',
 'मिलीलीटर',
 'ये',
 'ही',
 'तक',
 'स्थीरीकरण',
 'अन्तर्गत',
 'मिलिमीटर',
 'एककोशक

In [10]:
text_data=[]
for i in sentences:
    text_data.append(i.split())
text_data

[['जीवाणु', 'एक', 'एककोशिकीय', 'जीव', 'है'],
 ['इसका', 'आकार', 'कुछ', 'मिलिमीटर', 'तक', 'ही', 'होता', 'है'],
 ['इनकी',
  'आकृति',
  'गोल',
  'या',
  'मुक्तचक्राकार',
  'से',
  'लेकर',
  'छङा',
  'आदि',
  'आकार',
  'की',
  'हो',
  'सकती',
  'है'],
 ['ये',
  'प्रोकैरियोटिक',
  'कोशिका',
  'भित्तियुक्त',
  'एककोशकीय',
  'सरल',
  'जीव',
  'हैं',
  'जो',
  'प्रायः',
  'सर्वत्र',
  'पाये',
  'जाते',
  'है'],
 ['ये',
  'पृथ्वी',
  'पर',
  'मिट्टी',
  'में',
  'अम्लीय',
  'गर्म',
  'जलधाराओं',
  'में',
  'नाभिकीय',
  'पदार्थों',
  'में',
  'जल',
  'मेंभूपपड़ी',
  'में',
  'यहां',
  'तक',
  'की',
  'कार्बनिक',
  'पदार्थों',
  'में',
  'तथा',
  'पौधौं',
  'एवं',
  'जन्तुओं',
  'के',
  'शरीर',
  'के',
  'भीतर',
  'भी',
  'पाये',
  'जाते',
  'हैं'],
 ['साधारणतः',
  'एक',
  'ग्राम',
  'मिट्टी',
  'में',
  'करोड़',
  'जीवाणु',
  'कोष',
  'तथा',
  'मिलीलीटर',
  'जल',
  'में',
  'लाख',
  'जीवाणु',
  'पाएं',
  'जाते',
  'हैं'],
 ['संपूर्ण',
  'पृथ्वी',
  'पर',
  'अनुमानतः',
  'लगभग',
  'जीवाणु',
  'पाए

In [11]:
def MinWords():
    numWords = [len(sentence.split()) for sentence in sentences]
    return min(numWords)

In [12]:
MinWords()

5

In [13]:
def win_size():
    win_size=int(input('Enter window size: '))
    if(MinWords()<=win_size):
        print('operation not possible,select a smaller window_size')
        win_size()
    else:
        return win_size

In [14]:
window_size=win_size()

Enter window size: 4


In [15]:
w=[]
for i in sentences:
    i=i.split(' ') #if i is list
    for k in range(len(i)-window_size+1):
        for l in range(k+1,k+window_size+1):
            if l<=len(i)-1:
                w.append([i[k],i[l]])
w

[['जीवाणु', 'एक'],
 ['जीवाणु', 'एककोशिकीय'],
 ['जीवाणु', 'जीव'],
 ['जीवाणु', 'है'],
 ['एक', 'एककोशिकीय'],
 ['एक', 'जीव'],
 ['एक', 'है'],
 ['इसका', 'आकार'],
 ['इसका', 'कुछ'],
 ['इसका', 'मिलिमीटर'],
 ['इसका', 'तक'],
 ['आकार', 'कुछ'],
 ['आकार', 'मिलिमीटर'],
 ['आकार', 'तक'],
 ['आकार', 'ही'],
 ['कुछ', 'मिलिमीटर'],
 ['कुछ', 'तक'],
 ['कुछ', 'ही'],
 ['कुछ', 'होता'],
 ['मिलिमीटर', 'तक'],
 ['मिलिमीटर', 'ही'],
 ['मिलिमीटर', 'होता'],
 ['मिलिमीटर', 'है'],
 ['तक', 'ही'],
 ['तक', 'होता'],
 ['तक', 'है'],
 ['इनकी', 'आकृति'],
 ['इनकी', 'गोल'],
 ['इनकी', 'या'],
 ['इनकी', 'मुक्तचक्राकार'],
 ['आकृति', 'गोल'],
 ['आकृति', 'या'],
 ['आकृति', 'मुक्तचक्राकार'],
 ['आकृति', 'से'],
 ['गोल', 'या'],
 ['गोल', 'मुक्तचक्राकार'],
 ['गोल', 'से'],
 ['गोल', 'लेकर'],
 ['या', 'मुक्तचक्राकार'],
 ['या', 'से'],
 ['या', 'लेकर'],
 ['या', 'छङा'],
 ['मुक्तचक्राकार', 'से'],
 ['मुक्तचक्राकार', 'लेकर'],
 ['मुक्तचक्राकार', 'छङा'],
 ['मुक्तचक्राकार', 'आदि'],
 ['से', 'लेकर'],
 ['से', 'छङा'],
 ['से', 'आदि'],
 ['से', 'आकार'],
 ['लेकर', 'छङा

In [16]:
len(w)

549

In [17]:
w1=[x[::-1] for x in w]
w.extend(w1)
w

[['जीवाणु', 'एक'],
 ['जीवाणु', 'एककोशिकीय'],
 ['जीवाणु', 'जीव'],
 ['जीवाणु', 'है'],
 ['एक', 'एककोशिकीय'],
 ['एक', 'जीव'],
 ['एक', 'है'],
 ['इसका', 'आकार'],
 ['इसका', 'कुछ'],
 ['इसका', 'मिलिमीटर'],
 ['इसका', 'तक'],
 ['आकार', 'कुछ'],
 ['आकार', 'मिलिमीटर'],
 ['आकार', 'तक'],
 ['आकार', 'ही'],
 ['कुछ', 'मिलिमीटर'],
 ['कुछ', 'तक'],
 ['कुछ', 'ही'],
 ['कुछ', 'होता'],
 ['मिलिमीटर', 'तक'],
 ['मिलिमीटर', 'ही'],
 ['मिलिमीटर', 'होता'],
 ['मिलिमीटर', 'है'],
 ['तक', 'ही'],
 ['तक', 'होता'],
 ['तक', 'है'],
 ['इनकी', 'आकृति'],
 ['इनकी', 'गोल'],
 ['इनकी', 'या'],
 ['इनकी', 'मुक्तचक्राकार'],
 ['आकृति', 'गोल'],
 ['आकृति', 'या'],
 ['आकृति', 'मुक्तचक्राकार'],
 ['आकृति', 'से'],
 ['गोल', 'या'],
 ['गोल', 'मुक्तचक्राकार'],
 ['गोल', 'से'],
 ['गोल', 'लेकर'],
 ['या', 'मुक्तचक्राकार'],
 ['या', 'से'],
 ['या', 'लेकर'],
 ['या', 'छङा'],
 ['मुक्तचक्राकार', 'से'],
 ['मुक्तचक्राकार', 'लेकर'],
 ['मुक्तचक्राकार', 'छङा'],
 ['मुक्तचक्राकार', 'आदि'],
 ['से', 'लेकर'],
 ['से', 'छङा'],
 ['से', 'आदि'],
 ['से', 'आकार'],
 ['लेकर', 'छङा

In [18]:
len(w)

1098

In [19]:
a=np.zeros((len(vocab),len(vocab)))

In [20]:
df=pd.DataFrame(a,index=vocab,columns=vocab)

In [21]:
df

भीतर  पृथ्वी  तथा  मेंभूपपड़ी  जीवाणु  पाये  लगभग  यहां  बड़ा  \
भीतर         0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
पृथ्वी       0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
तथा          0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
मेंभूपपड़ी   0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
जीवाणु       0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
...          ...     ...  ...         ...     ...   ...   ...   ...   ...   
जाते         0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
जैसे         0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
साधारणतः     0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
जलधाराओं     0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
के           0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   

             को  ...  जीवाणुओं   हो    न  नाभिकीय  शाखा  जाते  जैसे  साधारणतः  \
भीतर        0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
पृथ्वी      0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
तथा         0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
मेंभूपपड़ी  0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
जीवाणु      0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
...         ...  ...       ...  ...  ...      ...   ...   ...   ...       ...   
जाते        0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
जैसे        0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
साधारणतः    0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
जलधाराओं    0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
के          0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   

            जलधाराओं   के  
भीतर             0.0  0.0  
पृथ्वी           0.0  0.0  
तथा              0.0  0.0  
मेंभूपपड़ी       0.0  0.0  
जीवाणु           0.0  0.0  
...              ...  ...  
जाते             0.0  0.0  
जैसे             0.0  0.0  
साधारणतः         0.0  0.0  
जलधाराओं         0.0  0.0  
के               0.0  0.0  

[110 rows x 110 columns]

In [22]:
for i in w:
    df.at[i[0],i[1]]+=1

In [23]:
sentences

['जीवाणु एक एककोशिकीय जीव है',
 'इसका आकार कुछ मिलिमीटर तक ही होता है',
 'इनकी आकृति गोल या मुक्तचक्राकार से लेकर छङा आदि आकार की हो सकती है',
 'ये प्रोकैरियोटिक कोशिका भित्तियुक्त एककोशकीय सरल जीव हैं जो प्रायः सर्वत्र पाये जाते है',
 'ये पृथ्वी पर मिट्टी में अम्लीय गर्म जलधाराओं में नाभिकीय पदार्थों में जल मेंभूपपड़ी में यहां तक की कार्बनिक पदार्थों में तथा पौधौं एवं जन्तुओं के शरीर के भीतर भी पाये जाते हैं',
 'साधारणतः एक ग्राम मिट्टी में करोड़ जीवाणु कोष तथा मिलीलीटर जल में लाख जीवाणु पाएं जाते हैं',
 'संपूर्ण पृथ्वी पर अनुमानतः लगभग जीवाणु पाएं जाते हैं',
 'जो संसार के बायोमास का एक बहुत बड़ा भाग है',
 'ये कई तत्वों के चक्र में बहुत महत्वपूर्ण भूमिका अदा करते हैं जैसे कि वायुमंडलिए नाइट्रोजन के स्थीरीकरण में',
 'हलाकि बहुत सारे वंश के जीवाणुओं का श्रेणी विभाजन भी नहीं हुआ है तथापि लगभग आधे जातियों को किसी न किसी प्रयोगशाला में उगाया जा चुका है',
 'जीवाणुओं का अध्ययन बैक्टिरियोलोजी के अन्तर्गत किया जाता है जो कि सूक्ष्मजैविकी की ही एक शाखा है']

In [24]:
df

भीतर  पृथ्वी  तथा  मेंभूपपड़ी  जीवाणु  पाये  लगभग  यहां  बड़ा  \
भीतर         0.0     0.0  0.0         0.0     0.0   1.0   0.0   0.0   0.0   
पृथ्वी       0.0     0.0  0.0         0.0     1.0   0.0   1.0   0.0   0.0   
तथा          0.0     0.0  0.0         0.0     1.0   0.0   0.0   0.0   0.0   
मेंभूपपड़ी   0.0     0.0  0.0         0.0     0.0   0.0   0.0   1.0   0.0   
जीवाणु       0.0     1.0  1.0         0.0     0.0   0.0   1.0   0.0   0.0   
...          ...     ...  ...         ...     ...   ...   ...   ...   ...   
जाते         1.0     0.0  0.0         0.0     2.0   0.0   1.0   0.0   0.0   
जैसे         0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
साधारणतः     0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
जलधाराओं     0.0     0.0  0.0         0.0     0.0   0.0   0.0   0.0   0.0   
के           2.0     0.0  1.0         0.0     0.0   1.0   0.0   0.0   0.0   

             को  ...  जीवाणुओं   हो    न  नाभिकीय  शाखा  जाते  जैसे  साधारणतः  \
भीतर        0.0  ...       0.0  0.0  0.0      0.0   0.0   1.0   0.0       0.0   
पृथ्वी      0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
तथा         0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
मेंभूपपड़ी  0.0  ...       0.0  0.0  0.0      1.0   0.0   0.0   0.0       0.0   
जीवाणु      0.0  ...       0.0  0.0  0.0      0.0   0.0   2.0   0.0       0.0   
...         ...  ...       ...  ...  ...      ...   ...   ...   ...       ...   
जाते        0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
जैसे        0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
साधारणतः    0.0  ...       0.0  0.0  0.0      0.0   0.0   0.0   0.0       0.0   
जलधाराओं    0.0  ...       0.0  0.0  0.0      1.0   0.0   0.0   0.0       0.0   
के          0.0  ...       2.0  0.0  0.0      0.0   0.0   1.0   1.0       0.0   

            जलधाराओं   के  
भीतर             0.0  2.0  
पृथ्वी           0.0  0.0  
तथा              0.0  1.0  
मेंभूपपड़ी       0.0  0.0  
जीवाणु           0.0  0.0  
...              ...  ...  
जाते             0.0  1.0  
जैसे             0.0  1.0  
साधारणतः         0.0  0.0  
जलधाराओं         0.0  0.0  
के               0.0  2.0  

[110 rows x 110 columns]

In [25]:
from numpy import array
from scipy.linalg import svd
from numpy import diag
from numpy import dot
# define a matrix
A = array(df)
print('Matrix A is: \n')
print(A)
# SVD
U, s, VT = svd(A)
print('*'*120)
print('Matrix U is: \n')
print(U)
print('*'*120)
Sigma = diag(s)
print('Matrix Sigma is: \n')
print(Sigma)
print('*'*120)
print('Matrix VT is: \n')
print(VT)

Matrix A is: 

[[0. 0. 0. ... 0. 0. 2.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [2. 0. 1. ... 0. 0. 2.]]
************************************************************************************************************************
Matrix U is: 

[[-4.03436505e-02  1.29511836e-01 -5.01967257e-02 ... -1.49052141e-01  9.02053812e-02 -1.75070151e-01]
 [-7.32828455e-02 -3.77783526e-02  1.97960402e-02 ... -2.28964908e-01 -1.45318055e-01  5.80445438e-02]
 [-1.91614346e-01 -4.59363382e-02 -7.98507318e-02 ... -5.52523163e-02 -1.49699982e-01 -8.33468156e-02]
 ...
 [-4.99986197e-02 -1.63978648e-02 -4.34951292e-04 ... -1.13738326e-01 -2.26703266e-01 -3.15552003e-02]
 [-1.35832584e-01 -8.84033560e-02 -7.14134309e-02 ...  1.21134239e-01  5.11015003e-02 -8.60318406e-02]
 [-2.03909783e-01  4.97095391e-01 -2.29150645e-01 ... -1.50068045e-02  4.49450158e-02 -3.28228864e-02]]
*********************************************************************

In [26]:
U.shape,Sigma.shape,VT.shape

((110, 110), (110, 110), (110, 110))

In [27]:
k=int(input('Enter k: '))
if(k>len(vocab) or k<1):
    print('operation not possible, select a k between 1 and ',len(vocab))
    raise SystemExit("Stop right there!")

Enter k: 50


In [28]:
U=U[:,:k]
Sigma=Sigma[:k,:k]
VT=VT[:k,:]

In [29]:
U.shape,Sigma.shape,VT.shape

((110, 50), (50, 50), (50, 110))

In [30]:
U_df=pd.DataFrame(U,index=vocab)
U_df

0         1         2         3         4         5   \
भीतर       -0.040344  0.129512 -0.050197  0.049387 -0.032024  0.013239   
पृथ्वी     -0.073283 -0.037778  0.019796  0.148381 -0.068688 -0.166236   
तथा        -0.191614 -0.045936 -0.079851 -0.039314 -0.037143 -0.039598   
मेंभूपपड़ी -0.117826 -0.072426 -0.003722 -0.106853  0.023048  0.032646   
जीवाणु     -0.187995 -0.049365  0.105705  0.240131 -0.251294 -0.236222   
...              ...       ...       ...       ...       ...       ...   
जाते       -0.083768  0.058907  0.056917  0.142357 -0.109438 -0.097663   
जैसे       -0.030756  0.072818  0.008594  0.027669 -0.079665  0.197979   
साधारणतः   -0.049999 -0.016398 -0.000435  0.002574 -0.017976 -0.030319   
जलधाराओं   -0.135833 -0.088403 -0.071413 -0.026104  0.014996  0.021309   
के         -0.203910  0.497095 -0.229151 -0.018268  0.056754  0.001755   

                  6         7         8         9   ...        40        41  \
भीतर       -0.068701 -0.076002  0.124143  0.213165  ... -0.117764  0.072737   
पृथ्वी     -0.050719  0.091080  0.019365 -0.155318  ... -0.013807 -0.130912   
तथा         0.000526  0.124960  0.137406  0.184979  ...  0.125065  0.018849   
मेंभूपपड़ी  0.048197  0.050235  0.057846  0.058070  ...  0.087287 -0.013839   
जीवाणु     -0.010184 -0.420080  0.111193  0.019713  ...  0.065076 -0.073166   
...              ...       ...       ...       ...  ...       ...       ...   
जाते       -0.023706  0.318969  0.054776  0.156199  ...  0.031894 -0.117901   
जैसे       -0.074665 -0.027578  0.059045 -0.067698  ...  0.065879 -0.013759   
साधारणतः    0.025810  0.016983  0.051951 -0.108196  ...  0.042074  0.029982   
जलधाराओं    0.009053  0.058851  0.166896 -0.069814  ...  0.056792 -0.000829   
के         -0.067601 -0.051098 -0.470623  0.073843  ... -0.045724 -0.095637   

                  42        43        44        45        46        47  \
भीतर       -0.074918  0.024754 -0.080406 -0.159175  0.159811 -0.312067   
पृथ्वी      0.055618  0.083085 -0.040084  0.043326 -0.061546  0.066822   
तथा         0.129503 -0.067513  0.042584  0.105452 -0.054575  0.230023   
मेंभूपपड़ी -0.091914  0.113827  0.101921 -0.014914  0.069304 -0.225645   
जीवाणु      0.044953 -0.018952  0.048472  0.048270 -0.031820 -0.076265   
...              ...       ...       ...       ...       ...       ...   
जाते        0.046677  0.028669  0.074520  0.027495  0.083413 -0.009344   
जैसे        0.069107  0.024703 -0.204432  0.438083  0.084569  0.023484   
साधारणतः    0.125046  0.248023  0.044888  0.021785 -0.030242 -0.115592   
जलधाराओं    0.041296 -0.174210 -0.000262  0.041262  0.020996  0.004321   
के         -0.072145 -0.011071 -0.060617  0.055149 -0.020157 -0.022497   

                  48        49  
भीतर       -0.216220 -0.037517  
पृथ्वी     -0.082195 -0.144141  
तथा        -0.109111  0.030037  
मेंभूपपड़ी -0.070382  0.324298  
जीवाणु      0.093125  0.096491  
...              ...       ...  
जाते       -0.034660 -0.061569  
जैसे       -0.225773  0.065673  
साधारणतः    0.032791 -0.138518  
जलधाराओं   -0.028402  0.081990  
के         -0.043466  0.039325  

[110 rows x 50 columns]